# Generated by Django 2.0.4 on 2018-08-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_tile',
            new_name='song_title',
        ),
    ]
