# Generated by Django 2.0.4 on 2018-08-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180809_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='album',
        ),
    ]
